# create an array airports of arrays containing the airport code and description
# based on dropdown options on http://apps.bts.gov/xml/ontimesummarystatistics/src/ddisp/OntimeSummarySelect.xml?tname=OntimeSummaryBothData

airports = []

airports.append(["ABI", "Abilene, TX - Abilene Regional (ABI)"])
airports.append(["BQN", "Aguadilla, PR - Rafael Hernandez (BQN)"])
airports.append(["CAK", "Akron-Canton-Massillon, OH - Akron-Canton (CAK)"])
airports.append(["ABY", "Albany, GA - Southwest Georgia Regional (ABY)"])
airports.append(["ALB", "Albany-Schenectady-Troy, NY - Albany International (ALB)"])
airports.append(["ABQ", "Albuquerque, NM - Albuquerque International (ABQ)"])
airports.append(["AEX", "Alexandria, LA - Alexandria International (AEX)"])
airports.append(["ABE", "Allentown-Bethlehem, PA - Lehigh Valley International (ABE)"])
airports.append(["AMA", "Amarillo, TX - Rick Husband Amarillo International (AMA)"])
airports.append(["ANC", "Anchorage, AK - Ted Stevens Anchorage International (ANC)"])
airports.append(["ANI", "Aniak, AK - Aniak (ANI)"])
airports.append(["ATW", "Appleton, WI - Outagamie County Regional (ATW)"])
airports.append(["ACV", "Arcata, CA - Arcata/Eureka (ACV)"])
airports.append(["AVL", "Asheville, NC - Asheville Regional (AVL)"])
airports.append(["ATL", "Atlanta-Sandy Springs-Marietta, GA - Hartsfield-Jackson Atlanta International (ATL)"])
airports.append(["ACY", "Atlantic City-Hammonton, NJ - Atlantic City International (ACY)"])
airports.append(["AGS", "Augusta-Richmond County, GA-SC - Augusta Regional (AGS)"])
airports.append(["AUS", "Austin-Round Rock, TX - Austin-Bergstrom International (AUS)"])
airports.append(["BFL", "Bakersfield, CA - Meadows Field (BFL)"])
airports.append(["BWI", "Baltimore-Towson, MD - Baltimore Washington International Thurgood Marshall (BWI)"])
airports.append(["BGR", "Bangor, ME - Bangor International (BGR)"])
airports.append(["BRW", "Barrow, AK - Wiley Post-Will Rogers Memorial (BRW)"])
airports.append(["BTR", "Baton Rouge, LA - Baton Rouge Metropolitan (BTR)"])
airports.append(["BPT", "Beaumont-Port Arthur, TX - Southeast Texas Regional (BPT)"])
airports.append(["BET", "Bethel, AK - Bethel (BET)"])
airports.append(["BIL", "Billings, MT - Billings Logan International (BIL)"])
airports.append(["BGM", "Binghamton, NY - Greater Binghamton (BGM)"])
airports.append(["BHM", "Birmingham-Hoover, AL - Birmingham-Shuttlesworth International (BHM)"])
airports.append(["BIS", "Bismarck, ND - Bismarck (BIS)"])
airports.append(["BMI", "Bloomington-Normal, IL - Central Illinois Regional (BMI)"])
airports.append(["BOI", "Boise City-Nampa, ID - Boise (BOI)"])
airports.append(["BOS", "Boston-Cambridge-Quincy, MA-NH - Logan International (BOS)"])
airports.append(["BZN", "Bozeman, MT - Gallatin Field (BZN)"])
airports.append(["SRQ", "Bradenton-Sarasota-Venice, FL - Sarasota Bradenton International (SRQ)"])
airports.append(["BRO", "Brownsville-Harlingen, TX - Brownsville South Padre Island International (BRO)"])
airports.append(["BQK", "Brunswick, GA - Glynn County (BQK)"])
airports.append(["BUF", "Buffalo-Niagara Falls, NY - Buffalo Niagara International (BUF)"])
airports.append(["BTV", "Burlington-South Burlington, VT - Burlington International (BTV)"])
airports.append(["BTM", "Butte, MT - Bert Mooney (BTM)"])
airports.append(["CPR", "Casper, WY - Casper/Natrona County International (CPR)"])
airports.append(["CDC", "Cedar City, UT - Cedar City Regional (CDC)"])
airports.append(["CID", "Cedar Rapids, IA - The Eastern Iowa (CID)"])
airports.append(["CMI", "Champaign-Urbana, IL - University of Illinois-Champaign Willard (CMI)"])
airports.append(["CRW", "Charleston, WV - Yeager (CRW)"])
airports.append(["CHS", "Charleston-North Charleston-Summerville, SC - Charleston International (CHS)"])
airports.append(["CLT", "Charlotte-Gastonia-Concord, NC-SC - Charlotte Douglas International (CLT)"])
airports.append(["CHO", "Charlottesville, VA - Charlottesville-Albemarle (CHO)"])
airports.append(["CHA", "Chattanooga, TN-GA - Chattanooga Metropolitan (CHA)"])
airports.append(["MDW", "Chicago-Naperville-Joliet, IL-IN-WI - Midway International (MDW)"])
airports.append(["ORD", "Chicago-Naperville-Joliet, IL-IN-WI - O'Hare International (ORD)"])
airports.append(["CIC", "Chico, CA - Chico Municipal (CIC)"])
airports.append(["CVG", "Cincinnati-Middleton, OH-KY-IN - Cincinnati/Northern Kentucky International (CVG)"])
airports.append(["CLE", "Cleveland-Elyria-Mentor, OH - Cleveland Hopkins International (CLE)"])
airports.append(["COD", "Cody, WY - Yellowstone Regional (COD)"])
airports.append(["CLL", "College Station-Bryan, TX - Easterwood (CLL)"])
airports.append(["COS", "Colorado Springs, CO - Colorado Springs (COS)"])
airports.append(["CAE", "Columbia, SC - Columbia Metropolitan (CAE)"])
airports.append(["CSG", "Columbus, GA-AL - Columbus (CSG)"])
airports.append(["GTR", "Columbus, MS - Golden Triangle Regional (GTR)"])
airports.append(["CMH", "Columbus, OH - Port Columbus International (CMH)"])
airports.append(["CDV", "Cordova, AK - Cordova-Mile 13 (CDV)"])
airports.append(["CRP", "Corpus Christi, TX - Corpus Christi International (CRP)"])
airports.append(["CEC", "Crescent City, CA - Jack Mc Namara Field (CEC)"])
airports.append(["DFW", "Dallas-Fort Worth-Arlington, TX - Dallas/Fort Worth International (DFW)"])
airports.append(["DAL", "Dallas-Fort Worth-Arlington, TX - Dallas Love Field (DAL)"])
airports.append(["DAY", "Dayton, OH - Dayton International (DAY)"])
airports.append(["SCC", "Deadhorse, AK - Deadhorse (SCC)"])
airports.append(["DAB", "Deltona-Daytona Beach-Ormond Beach, FL - Daytona Beach International (DAB)"])
airports.append(["DEN", "Denver-Aurora-Broomfield, CO - Denver International (DEN)"])
airports.append(["DSM", "Des Moines-West Des Moines, IA - Des Moines International (DSM)"])
airports.append(["DTW", "Detroit-Warren-Livonia, MI - Detroit Metro (DTW)"])
airports.append(["DLG", "Dillingham, AK - Dillingham (DLG)"])
airports.append(["DHN", "Dothan, AL - Dothan Regional (DHN)"])
airports.append(["DBQ", "Dubuque, IA - Dubuque Regional (DBQ)"])
airports.append(["DLH", "Duluth, MN-WI - Duluth International (DLH)"])
airports.append(["DRO", "Durango, CO - Durango-La Plata County (DRO)"])
airports.append(["DUT", "Dutch Harbor, AK - Dutch Harbor (DUT)"])
airports.append(["EGE", "Eagle, CO - Eagle County Regional (EGE)"])
airports.append(["IPL", "El Centro, CA - Imperial County (IPL)"])
airports.append(["ELP", "El Paso, TX - El Paso International (ELP)"])
airports.append(["EKO", "Elko, NV - Elko Regional (EKO)"])
airports.append(["ELM", "Elmira, NY - Elmira Corning Regional (ELM)"])
airports.append(["ERI", "Erie, PA - Erie International Tom Ridge Field (ERI)"])
airports.append(["EUG", "Eugene-Springfield, OR - Eugene (EUG)"])
airports.append(["EVV", "Evansville, IN-KY - Evansville Regional (EVV)"])
airports.append(["FAI", "Fairbanks, AK - Fairbanks International (FAI)"])
airports.append(["FAR", "Fargo, ND-MN - Hector International (FAR)"])
airports.append(["FAY", "Fayetteville, NC - Fayetteville (FAY)"])
airports.append(["XNA", "Fayetteville-Springdale-Rogers, AR-MO - Northwest Arkansas Regional (XNA)"])
airports.append(["FNT", "Flint, MI - Bishop International (FNT)"])
airports.append(["FLO", "Florence, SC - Florence Regional (FLO)"])
airports.append(["FSM", "Fort Smith, AR-OK - Fort Smith Regional (FSM)"])
airports.append(["FWA", "Fort Wayne, IN - Fort Wayne International (FWA)"])
airports.append(["FAT", "Fresno, CA - Fresno Air Terminal (FAT)"])
airports.append(["FYI", "Fresno, CA - Fresno Yosemite International (FYI)"])
airports.append(["RSW", "Ft. Myers, FL - Southwest Florida International (RSW)"])
airports.append(["GNV", "Gainesville, FL - Gainesville Regional (GNV)"])
airports.append(["GFK", "Grand Forks, ND-MN - Grand Forks International (GFK)"])
airports.append(["GJT", "Grand Junction, CO - Grand Junction Regional (GJT)"])
airports.append(["GRR", "Grand Rapids-Wyoming, MI - Gerald R. Ford International (GRR)"])
airports.append(["GTF", "Great Falls, MT - Great Falls International (GTF)"])
airports.append(["GRB", "Green Bay, WI - Austin Straubel International (GRB)"])
airports.append(["GSO", "Greensboro-High Point, NC - Piedmont Triad International (GSO)"])
airports.append(["GSP", "Greenville-Mauldin-Easley, SC - Greenville-Spartanburg International (GSP)"])
airports.append(["GPT", "Gulfport-Biloxi, MS - Gulfport-Biloxi International (GPT)"])
airports.append(["GUC", "Gunnison, CO - Gunnison-Crested Butte Regional (GUC)"])
airports.append(["GST", "Gustavus, AK - Gustavus (GST)"])
airports.append(["SUN", "Hailey, ID - Friedman Memorial (SUN)"])
airports.append(["HRL", "Harlingen, TX - Valley International (HRL)"])
airports.append(["MDT", "Harrisburg-Carlisle, PA - Harrisburg International (MDT)"])
airports.append(["BDL", "Hartford-West Hartford-East Hartford, CT - Bradley International (BDL)"])
airports.append(["HLN", "Helena, MT - Helena Regional (HLN)"])
airports.append(["ITO", "Hilo, Hawaii, HI - Hilo International (ITO)"])
airports.append(["HNL", "Honolulu, Oahu, HI - Honolulu International (HNL)"])
airports.append(["EFD", "Houston-Sugar Land-Bayton, TX - Ellington Field (EFD)"])
airports.append(["HOU", "Houston-Sugar Land-Bayton, TX - William P. Hobby (HOU)"])
airports.append(["IAH", "Houston-Sugar Land-Bayton, TX - George Bush Intercontinental (IAH)"])
airports.append(["HTS", "Huntington-Ashland, WV-KY-OH - Tri-State (HTS)"])
airports.append(["HSV", "Huntsville, AL - Huntsville International (HSV)"])
airports.append(["IDA", "Idaho Falls, ID - Idaho Falls Regional (IDA)"])
airports.append(["IND", "Indianapolis-Carmel, IN - Indianapolis International (IND)"])
airports.append(["IYK", "Inyokern, CA - Inyokern (IYK)"])
airports.append(["ITH", "Ithaca, NY - Ithaca (ITH)"])
airports.append(["JAN", "Jackson, MS - Jackson-Evers International (JAN)"])
airports.append(["JAC", "Jackson, WY - Jackson Hole (JAC)"])
airports.append(["JAX", "Jacksonville, FL - Jacksonville International (JAX)"])
airports.append(["OAJ", "Jacksonville, NC - Albert J. Ellis (OAJ)"])
airports.append(["TRI", "Johnson City-Kingsport-Bristol, TN-VA - Tri-Cities Regional (TRI)"])
airports.append(["JNU", "Juneau, AK - Juneau International (JNU)"])
airports.append(["OGG", "Kahului, Maui, HI - Kahului (OGG)"])
airports.append(["AZO", "Kalamazoo-Portage, MI - Kalamazoo/Battle Creek International (AZO)"])
airports.append(["FCA", "Kalispell, MT - Glacier Park International (FCA)"])
airports.append(["MCI", "Kansas City, MO-KS - Kansas City International (MCI)"])
airports.append(["KTN", "Ketchikan, AK - Ketchikan International (KTN)"])
airports.append(["EYW", "Key West, FL - Key West International (EYW)"])
airports.append(["ILE", "Killeen-Temple-Fort Hood, TX - Killeen Municipal (ILE)"])
airports.append(["AKN", "King Salmon, AK - King Salmon (AKN)"])
airports.append(["TYS", "Knoxville, TN - McGhee Tyson (TYS)"])
airports.append(["ADQ", "Kodiak, AK - Kodiak (ADQ)"])
airports.append(["KOA", "Kona, Hawaii, HI - Kona International (KOA)"])
airports.append(["OTZ", "Kotzebue, AK - Ralph Wien Memorial (OTZ)"])
airports.append(["LSE", "La Crosse, WI-MN - La Cross Municipal (LSE)"])
airports.append(["LFT", "Lafayette, LA - Lafayette Regional (LFT)"])
airports.append(["LCH", "Lake Charles, LA - Lake Charles Regional (LCH)"])
airports.append(["LAN", "Lansing-East Lansing, MI - Capital Region International (LAN)"])
airports.append(["LRD", "Laredo, TX - Laredo International (LRD)"])
airports.append(["LAS", "Las Vegas-Paradise, NV - McCarran International (LAS)"])
airports.append(["LAW", "Lawton, OK - Lawton-Fort Sill Regional (LAW)"])
airports.append(["LWB", "Lewisburg, WV - Greenbrier Valley (LWB)"])
airports.append(["LEX", "Lexington-Fayette, KY - Blue Grass (LEX)"])
airports.append(["LIH", "Lihue, Kauai, HI - Lihue (LIH)"])
airports.append(["LNK", "Lincoln, NE - Lincoln (LNK)"])
airports.append(["LIT", "Little Rock-North Little Rock-Conway, AR - Little Rock National (LIT)"])
airports.append(["GGG", "Longview, TX - East Texas Regional (GGG)"])
airports.append(["BUR", "Los Angeles-Long Beach-Santa Ana, CA - Bob Hope (BUR)"])
airports.append(["SNA", "Los Angeles-Long Beach-Santa Ana, CA - John Wayne (SNA)"])
airports.append(["LGB", "Los Angeles-Long Beach-Santa Ana, CA - Long Beach (LGB)"])
airports.append(["LAX", "Los Angeles-Long Beach-Santa Ana, CA - Los Angeles International (LAX)"])
airports.append(["SDF", "Louisville/Jefferson County, KY-IN - Louisville International (SDF)"])
airports.append(["LBB", "Lubbock, TX - Lubbock International (LBB)"])
airports.append(["LYH", "Lynchburg, VA - Lynchburg Regional (LYH)"])
airports.append(["MCN", "Macon, GA - Middle Georgia Regional (MCN)"])
airports.append(["MSN", "Madison, WI - Dane County Regional (MSN)"])
airports.append(["MHT", "Manchester-Nashua, NH - Manchester-Boston Regional (MHT)"])
airports.append(["MQT", "Marquette, MI - Marquette County (MQT)"])
airports.append(["MFE", "McAllen-Edinburg-Mission, TX - McAllen International (MFE)"])
airports.append(["MFR", "Medford, OR - Rogue Valley International-Medford (MFR)"])
airports.append(["MLB", "Melbourne, FL - Melbourne International (MLB)"])
airports.append(["MEM", "Memphis, TN-MS-AR - Memphis International (MEM)"])
airports.append(["MEI", "Meridian, MS - Key Field (MEI)"])
airports.append(["FLL", "Miami-Fort Lauderdale-Pompano Beach, FL - Ft. Lauderdale-Hollywood International (FLL)"])
airports.append(["MIA", "Miami-Fort Lauderdale-Pompano Beach, FL - Miami International (MIA)"])
airports.append(["PBI", "Miami-Fort Lauderdale-Pompano Beach, FL - Palm Beach International (PBI)"])
airports.append(["MAF", "Midland, TX - Midland International (MAF)"])
airports.append(["MKE", "Milwaukee-Waukesha-West Allis, WI - General Mitchell International (MKE)"])
airports.append(["MSP", "Minneapls-St. Paul-Bloomington, MN-WI - Minneapolis-St. Paul International (MSP)"])
airports.append(["MOT", "Minot, ND - Minot International (MOT)"])
airports.append(["MSO", "Missoula, MT - Missoula International (MSO)"])
airports.append(["MOB", "Mobile, AL - Mobile Regional (MOB)"])
airports.append(["MOD", "Modesto, CA - Modesto City-County (MOD)"])
airports.append(["MLI", "Moline, IL - Quad-City International (MLI)"])
airports.append(["MLU", "Monroe, LA - Monroe Regional (MLU)"])
airports.append(["MRY", "Monterey, CA - Monterey Peninsula (MRY)"])
airports.append(["MGM", "Montgomery, AL - Montgomery Regional (MGM)"])
airports.append(["MTJ", "Montrose, CO - Montrose Regional (MTJ)"])
airports.append(["MYR", "Myrtle Beach-North Myrtle Beach-Conway, SC - Myrtle Beach International (MYR)"])
airports.append(["ACK", "Nantucket, MA - Nantucket Memorial (ACK)"])
airports.append(["BNA", "Nashville-Davidson-Murfreesboro-Franklin, TN - Nashville International (BNA)"])
airports.append(["HVN", "New Haven-Milford, CT - Tweed-New Haven (HVN)"])
airports.append(["MSY", "New Orleans-Metairie-Kenner, LA - Louis Armstrong New Orleans International (MSY)"])
airports.append(["SWF", "New York-New Jersey-Long Island, NY-NJ-PA - Stewart International (SWF)"])
airports.append(["ISP", "New York-New Jersey-Long Island, NY-NJ-PA - Long Island MacArthur (ISP)"])
airports.append(["JFK", "New York-New Jersey-Long Island, NY-NJ-PA - John F. Kennedy International (JFK)"])
airports.append(["EWR", "New York-New Jersey-Long Island, NY-NJ-PA - Newark Liberty International (EWR)"])
airports.append(["LGA", "New York-New Jersey-Long Island, NY-NJ-PA - LaGuardia (LGA)"])
airports.append(["OME", "Nome, AK - Nome (OME)"])
airports.append(["OGD", "Ogden, UT - Ogden-Hinckley Municipal (OGD)"])
airports.append(["OKC", "Oklahoma City, OK - Will Rogers World (OKC)"])
airports.append(["OMA", "Omaha-Council Bluffs, NE-IA - Eppley (OMA)"])
airports.append(["MCO", "Orlando-Kissimmee, FL - Orlando International (MCO)"])
airports.append(["OXR", "Oxnard-Thousand Oaks-Ventura, CA - Oxnard (OXR)"])
airports.append(["PSP", "Palm Springs-Riverside-San Bernardino-Ontario, CA - Palm Springs International (PSP)"])
airports.append(["PFN", "Panama City-Lynn Haven-Panama City Beach, FL - Northwest Florida Beaches International (PFN)"])
airports.append(["PSC", "Pasco, WA - Tri-Cities (PSC)"])
airports.append(["PNS", "Pensacola-Ferry Pass-Brent, FL - Pensacola Gulf Coast Regional (PNS)"])
airports.append(["PIA", "Peoria, IL - General Wayne A. Downing Peoria International (PIA)"])
airports.append(["PSG", "Petersburg, AK - Petersburg James A. Johnson (PSG)"])
airports.append(["PHL", "Philadelphia-Camden-Wilmington, PA-NJ-DE-MD - Philadelphia International (PHL)"])
airports.append(["PHX", "Phoenix-Mesa-Scottsdale, AZ - Phoenix Sky Harbor International (PHX)"])
airports.append(["PIT", "Pittsburgh, PA - Pittsburgh International (PIT)"])
airports.append(["PIH", "Pocatello, ID - Pocatello Regional (PIH)"])
airports.append(["PWM", "Portland-South Portland-Biddeford, ME - Portland International (PWM)"])
airports.append(["PDX", "Portland-Vancouver-Beaverton, OR-WA - Portland International (PDX)"])
airports.append(["PVD", "Providence-New Bedford-Fall River, RI-MA - T. F. Green International (PVD)"])
airports.append(["PVU", "Provo-Orem, UT - Provo Municipal (PVU)"])
airports.append(["RDU", "Raleigh-Cary-Durham-Chapel Hill, NC - Raleigh-Durham International (RDU)"])
airports.append(["RAP", "Rapid City, SD - Rapid City Regional (RAP)"])
airports.append(["RDD", "Redding, CA - Redding Municipal (RDD)"])
airports.append(["RDM", "Redmond, OR - Roberts Field (RDM)"])
airports.append(["RNO", "Reno-Sparks, NV - Reno-Tahoe International (RNO)"])
airports.append(["RIC", "Richmond, VA - Richmond International (RIC)"])
airports.append(["ONT", "Riverside-San Bernardino-Ontario, CA - LA/Ontario International (ONT)"])
airports.append(["ROA", "Roanoke, VA - Roanoke Regional (ROA)"])
airports.append(["RST", "Rochester, MN - Rochester International (RST)"])
airports.append(["ROC", "Rochester, NY - Greater Rochester International (ROC)"])
airports.append(["SAC", "Sacramento-Arden-Arcade-Roseville, CA - Sacramento Executive (SAC)"])
airports.append(["SMF", "Sacramento-Arden-Arcade-Roseville, CA - Sacramento International (SMF)"])
airports.append(["MBS", "Saginaw-Saginaw Township North, MI - MBS International (MBS)"])
airports.append(["SPN", "Saipan, Mariana Islands - Saipan International (SPN)"])
airports.append(["SLC", "Salt Lake City, UT - Salt Lake City International (SLC)"])
airports.append(["SJT", "San Angelo, TX - San Angelo Regional - Mathis Field (SJT)"])
airports.append(["SAT", "San Antonio, TX - San Antonio International (SAT)"])
airports.append(["CLD", "San Diego-Carlsbad-San Marcos, CA - McClellan-Palomar (CLD)"])
airports.append(["SAN", "San Diego-Carlsbad-San Marcos, CA - San Diego International (SAN)"])
airports.append(["OAK", "San Francisco-Oakland-Freemont, CA - Oakland International (OAK)"])
airports.append(["SFO", "San Francisco-Oakland-Freemont, CA - San Francisco International (SFO)"])
airports.append(["SJC", "San Jose-Sunnyvale-Santa Clara, CA - Norman Y. Mineta San Jose International (SJC)"])
airports.append(["SJU", "San Juan-Caguas-Guaynabo, PR - Luis Munoz Marin International (SJU)"])
airports.append(["SBP", "San Luis Obispo-Paso Robles, CA - San Luis Obispo County Regional (SBP)"])
airports.append(["SBA", "Santa Barbara-Santa Maria-Goleta, CA - Santa Barbara Municipal (SBA)"])
airports.append(["SMX", "Santa Maria, CA - Santa Maria Public (SMX)"])
airports.append(["SAV", "Savannah, GA - Savannah Hilton Head International (SAV)"])
airports.append(["AVP", "Scranton-Wilkes-Barre, PA - Wilkes-Barre/Scranton International (AVP)"])
airports.append(["SEA", "Seattle-Tacoma-Bellevue, WA - Seattle-Tacoma International (SEA)"])
airports.append(["SHV", "Shreveport-Bossier City, LA - Shreveport Regional (SHV)"])
airports.append(["SUX", "Sioux City, IA-NE-SD - Sioux Gateway (SUX)"])
airports.append(["FSD", "Sioux Falls, SD - Sioux Falls Regional (FSD)"])
airports.append(["SIT", "Sitka, AK - Sitka Rocky Gutierrez (SIT)"])
airports.append(["SBN", "South Bend-Mishawaka, IN-MI - South Bend Regional (SBN)"])
airports.append(["GEG", "Spokane, WA - Spokane International (GEG)"])
airports.append(["SGF", "Springfield, MO - Springfield-Branson National (SGF)"])
airports.append(["STX", "St. Croix, Virgin Islands - Henry E. Rholsen (STX)"])
airports.append(["SGU", "St. George, UT - St. George Municipal (SGU)"])
airports.append(["STL", "St. Louis, MO-IL - Lambert-St Louis International (STL)"])
airports.append(["KSM", "St. Mary's, AK - St Mary's County Regional (KSM)"])
airports.append(["STT", "St. Thomas, Virgin Islands - Cyril E. King (STT)"])
airports.append(["SCE", "State College, PA - University Park (SCE)"])
airports.append(["HDN", "Steamboat Springs, CO - Yampa Valley Regional (HDN)"])
airports.append(["SYR", "Syracuse, NY - Syracuse Hancock International (SYR)"])
airports.append(["TLH", "Tallahassee, FL - Tallahassee Regional (TLH)"])
airports.append(["PIE", "Tampa-St. Petersburg-Clearwater, FL - St Petersburg-Clearwater International (PIE)"])
airports.append(["TPA", "Tampa-St. Petersburg-Clearwater, FL - Tampa International (TPA)"])
airports.append(["GUM", "Tamuning, Guam - A. B. Won Pat International (GUM)"])
airports.append(["TXK", "Texarkana, TX-Texarkana, AR - Texarkana Regional / Webb Field (TXK)"])
airports.append(["TOL", "Toledo, OH - Toledo Express (TOL)"])
airports.append(["TVC", "Traverse City, MI - Cherry Capital (TVC)"])
airports.append(["TUS", "Tucson, AZ - Tucson International (TUS)"])
airports.append(["TUL", "Tulsa, OK - Tulsa International (TUL)"])
airports.append(["TWF", "Twin Falls, ID - Joslin Field-Magic Valley Regional (TWF)"])
airports.append(["TYR", "Tyler, TX - Tyler Pounds Field (TYR)"])
airports.append(["VLD", "Valdosta, GA - Valdosta Regional (VLD)"])
airports.append(["VPS", "Valparaiso, FL - Eglin Air Force Base (VPS)"])
airports.append(["VCT", "Victoria, TX - Victoria Regional (VCT)"])
airports.append(["ORF", "Virginia Beach-Norfolk-Newport News, VA - Norfolk International (ORF)"])
airports.append(["PHF", "Virginia Beach-Norfolk-Newport News, VA - Newport News/Williamsburg International (PHF)"])
airports.append(["VIS", "Visalia-Porterville, CA - Visalia Muni (VIS)"])
airports.append(["ACT", "Waco, TX - Waco Regional (ACT)"])
airports.append(["DCA", "Washington-Arlington-Alexandria, DC-VA-MD-WV - Ronald Reagan Washington National (DCA)"])
airports.append(["IAD", "Washington-Arlington-Alexandria, DC-VA-MD-WV - Dulles International (IAD)"])
airports.append(["ALO", "Waterloo-Cedar Falls, IA - Waterloo Regional (ALO)"])
airports.append(["HPN", "White Plains, NY - Westchester County (HPN)"])
airports.append(["SPS", "Wichita Falls, TX - Wichita Falls Municipal (SPS)"])
airports.append(["ICT", "Wichita, KS - Wichita Mid-Continent (ICT)"])
airports.append(["ILM", "Wilmington, NC - Wilmington International (ILM)"])
airports.append(["WRG", "Wrangell, AK - Wrangell (WRG)"])
airports.append(["YAK", "Yakutat, AK - Yakutat (YAK)"])
airports.append(["YUM", "Yuma, AZ - Yuma International (YUM)"])